// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/hair-types": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/hair-types";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/hair-types.tsx": {
    id: "routes/hair-types";
    page: "/hair-types";
  };
};